---
apiVersion: team.github.upbound.io/v1alpha1
kind: Team
metadata:
  name: {{ teamName | lower }}
  namespace: github-resources
spec:
  deletionPolicy: Orphan
  forProvider:
    name: {{ teamName }}
    
  providerConfigRef:
    name:  {{ orgName | lower }}

