---
name: Read Vault Secrets
description: "... it reads secrets from Vault?"
inputs:
  address:
    description: "the address of a deployed vault server"
    required: false
    default: https://vault.rancher.kitchen
  secrets:
    description: "the secrets to fetch from the vault server"
    required: false
    default: secret/data/github-actions/test status
  exportEnv:
    description: "Whether or not export secrets as environment variables."
    required: false
    default: true
  exportToken:
    description: "Whether or not export Vault token as environment variables."
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Read Secrets from Vault
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        method: jwt
        url: ${{ inputs.address }}
        path: ${{ github.repository_owner }}
        role: ${{ github.event.repository.name }}
        secrets: ${{ inputs.secrets }}
        exportEnv: ${{ inputs.exportEnv }}
        exportToken: ${{ inputs.exportToken }}
