---
name: Read Vault Secrets
description: "... it reads secrets from Vault?"
inputs:
  address:
    description: "the address of a deployed vault server"
    required: false
    default: https://vault.rancher.kitchen
  secrets:
    description: "the secrets to fetch from the vault server"
    required: false
    default: secret/data/github-actions/test status
outputs:
  declared:
    description: "a declared output"
    value: ${{ steps.output.outputs.declared }}
runs:
  using: composite
  steps:
    - name: Read Secrets from Vault
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        method: jwt
        url: ${{ inputs.address }}
        path: ${{ github.repository_owner }}
        role: ${{ github.event.repository.name }}
        secrets: ${{ inputs.secrets }}
        exportEnv: false
        exportToken: false
        outputToken: false
    - name: GitHub Script
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable("ACTIONS_ID_TOKEN_REQUEST_TOKEN", "DISCARDED");
          core.setOutput("declared", "success");
          core.setOutput("undeclared", "success");
          for (const [key, value] of Object.entries(${{ toJSON(steps.vault.outputs) }})) {
            core.setOutput(key, value);
          }
