name: Homebrew

on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
    paths: .github/workflows/homebrew.yaml

jobs:
  fetch-installer:
    container: alpine
    runs-on: repo-${{ github.repository_id }}-arm64-k8s
    # runs-on: runs-on,runner=1cpu-linux-arm64,run-id=${{ github.run_id }}
    steps:
      - run: |
          wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
          base64 install.sh
