name: Homebrew

on:
  workflow_call: {}
  workflow_dispatch: {}
  push:
    paths: .github/workflows/homebrew.yaml

jobs:
  install:
    container: registry.suse.com/bci/bci-base:15.5.36.14.1
    runs-on: repo-${{ github.repository_id }}-amd64-k8s
    # runs-on: runs-on,runner=1cpu-linux-arm64,run-id=${{ github.run_id }}
    steps:
      - run: |
          zypper install --no-confirm git-core
          env NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
