name: PodInfo VPN Tunnel Access with Tailscale

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/podinfo-vpn-tunnel-access-tailscale.yaml
  workflow_dispatch:

jobs:
  access-podinfo:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sudo sh
          sudo tailscale up \
            --login-server=https://headscale.rancher.kitchen \
            --authkey=${{ secrets.TAILSCALE_AUTHKEY }} \
            --hostname=github-runner-${{ github.run_id }} \
            --accept-routes \
            --accept-dns 
          echo "Tailscale connection status:"
          tailscale status
          echo "Tailscale IP routes:"
          ip route
      
      - name: Wait for Tailscale connection
        run: |
          echo "Waiting for Tailscale to connect..."
          sleep 10
          tailscale status
      
      - name: Access podinfo via IP directly
        run: |
          echo "Accessing podinfo using direct IP..."
          RESPONSE=$(curl -s http://10.100.70.134:9898/api/info)
          
          echo "Response from podinfo service:"
          echo "$RESPONSE" | jq .
        
          if echo "$RESPONSE" | jq -e '.hostname' > /dev/null; then
            echo "✅ Successfully accessed podinfo service via IP!"
          else
            echo "❌ Failed to get valid response from podinfo via IP"
            exit 1
          fi
          
      - name: Access podinfo via DNS name
        run: |
          echo "Accessing podinfo using DNS name..."
          RESPONSE=$(curl -s http://backend-podinfo.ts.rancher.kitchen:9898/api/info)
          
          echo "Response from podinfo service:"
          echo "$RESPONSE" | jq .
        
          if echo "$RESPONSE" | jq -e '.hostname' > /dev/null; then
            echo "✅ Successfully accessed podinfo service via DNS name!"
          else
            echo "❌ Failed to get valid response from podinfo via DNS name"
            exit 1
          fi
          
      # - name: Access podinfo via Cluster DNS
      #   run: |
      #     echo "Accessing podinfo using Cluster DNS name..."
      #     RESPONSE=$(curl -s http://backend-podinfo.podinfo.svc.cluster.local:9898/api/info)
          
      #     echo "Response from podinfo service:"
      #     echo "$RESPONSE" | jq .
        
      #     if echo "$RESPONSE" | jq -e '.hostname' > /dev/null; then
      #       echo "✅ Successfully accessed podinfo service via  Cluster DNS name!"
      #     else
      #       echo "❌ Failed to get valid response from podinfo via  Cluster DNS name"
      #       exit 1
      #     fi
          
      - name: Cleanup Tailscale
        if: always()
        run: |
          echo "Cleaning up Tailscale connection..."
          sudo tailscale logout || true
          sudo systemctl stop tailscaled || true
