---
name: Public IP Test

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/public-ip.yaml

jobs:
  self-hosted-org-vm:
    strategy:
      matrix:
        architecture:
        - x64
        - arm64
        cpu:
        - 1cpu
        - 2cpu
        - 4cpu
        os:
        - linux
    runs-on: runs-on,runner=${{ matrix.cpu }}-${{ matrix.os }}-${{ matrix.architecture }},run-id=${{ github.run_id }}
    steps:
    - name: Get Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
