---
name: Runner Matrix

on:
  workflow_call:
    inputs:
      github-hosted:
        type: boolean
        default: true
      self-hosted:
        type: boolean
        default: true
      containers:
        type: boolean
        default: true
      virtual-machines:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      github-hosted:
        type: boolean
        default: true
      self-hosted:
        type: boolean
        default: true
      containers:
        type: boolean
        default: true
      virtual-machines:
        type: boolean
        default: true

jobs:
  build:
    steps:
    - uses: cloudposse/github-action-jq@v0
      with:
        input: |
          { "inputs": ${{ inputs }} }
        script: .
