---
name: Select Runners

on:
  workflow_dispatch:
    inputs:
      github-hosted:
        type: boolean
        default: true
      self-hosted:
        type: boolean
        default: true
      containers:
        type: boolean
        default: true
      virtual-machines:
        type: boolean
        default: true
      amd64:
        type: boolean
        default: true
      arm64:
        type: boolean
        default: true
      kubernetes:
        type: boolean
        default: true
      github-runner:
        type: string
        default: ubuntu-22.04
      default-container:
        type: string
        default: ubuntu:22.04
jobs:
  select:
    runs-on: ubuntu-22.04
    outputs:
      github-hosted: ${{ steps.github-hosted.outputs.output }}
    steps:
    - name: github
      uses: mikefarah/yq@v4
      with:
        cmd: |
          echo '${{ toJson(inputs) }}' | yq '
            { "inputs": ., "outputs": [] }
            | { "container": .inputs.default-container } as $container
            | with(select(.inputs.github-hosted and .inputs.arm64);
                { "runs-on": .inputs.github-runner } as $runs-on
                | .outputs += $runs-on
                | with(select(.inputs.containers);
                    .outputs += ( $runs-on * $container )
                  )
              )
          '
