---
name: Select Runners

on:
  workflow_dispatch:
    inputs:
      arch/amd64:
        type: boolean
        default: true
      arch/arm64:
        type: boolean
        default: true
      pool/org:
        type: boolean
        default: true
      pool/repo:
        type: boolean
        default: true
      using/containers:
        type: boolean
        default: true
      using/virtual-machines:
        type: boolean
        default: true
jobs:
  select:
    runs-on: ubuntu-22.04
    outputs:
      self-hosted-containers: ${{ steps.self-hosted-containers.outputs.output }}
    steps:
    - name: self-hosted-containers
      uses: mikefarah/yq@v4
      with:
        cmd: |
          echo '${{ toJson(inputs) }}' | yq --output-format=json --indent=0 '
            {
              "inputs": with_entries(.key |= downcase),
              "matrix": {
                "arch": [],
                "pool": [],
                "uses": [],
                "runtime": []
              },
              "outputs": []
            }
            | with(select(.inputs.arch/* or .inputs.arch/amd64 or .inputs.arch/x86_64 or .inputs.arch/x64); .matrix.arch += "amd64")
            | with(select(.inputs.arch/* or .inputs.arch/arm64 or .inputs.arch/aarch64); .matrix.arch += "arm64")
            | with(select(.inputs.pool/* or .inputs.pool/org);  .matrix.pool += "org-${{ github.repository_owner_id }}")
            | with(select(.inputs.pool/* or .inputs.pool/repo); .matrix.pool += "repo-${{ github.repository_id }}")
            | with(select(.inputs.using/containers); .matrix.runtime += "k8s")
            | .inputs  ref $inputs
            | .matrix  ref $matrix
            | .outputs ref $outputs
            | with($matrix.pool[];
                . ref $pool
                | with($matrix.arch[];
                    . ref $arch
                    | with($matrix.runtime[];
                        . ref $runtime
                        | with([$pool, $arch, $runtime] | join("-");
                            . ref $runs-on
                            | $outputs += { "runs-on": $runs-on }
                          )
                      )
                  )
              )
          '
