---
name: Vault Testcase
on:
  push:
    branches:
    - test-leak-credentials
jobs:
  github-hosted:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-22.04
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test key | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        echo "${{ env.PROOF_OF_CONCEPT }}"
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"

  