name: Vault VPN Tunnel
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/vault-vpn-tunnel.yaml
  workflow_dispatch:

jobs:
  access-services:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/
      
      - name: Establish secure connection through Cloudflare
        run: |
          export CLOUDFLARE_ACCESS_CLIENT_ID="${{ secrets.CLOUDFLARE_ACCESS_CLIENT_ID }}"
          export CLOUDFLARE_ACCESS_CLIENT_SECRET="${{ secrets.CLOUDFLARE_ACCESS_CLIENT_SECRET }}"
          cloudflared access tcp --hostname podinfo.rancher.io --url localhost:9898 &
          echo "TUNNEL_PID=$!" >> $GITHUB_ENV
          sleep 5  
      
      - name: Access service via secure tunnel
        run: |
          curl http://localhost:9898/api/info
          
      - name: Terminate tunnel
        if: always()
        run: |
          kill ${{ env.TUNNEL_TUNNEL_PID }} || true
