---
name: Vault Testcase
on:
  push:
    branches:
    - main
    - vault
jobs:
  github-hosted:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-22.04
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-org-amd64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [org--rancher-eio--amd64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-org-arm64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [org--rancher-eio--arm64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-repo-amd64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: repo--${{ github.repository_id }}--amd64
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-repo-arm64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: repo--${{ github.repository_id }}--arm64
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-runs-on-arm64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: runs-on,runner=2cpu-linux-arm64,run-id=${{ github.run_id }}
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-runs-on-arm64-embiggened-disks:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: runs-on,runner=2cpu-linux-arm64,hdd=334,run-id=${{ github.run_id }}
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-runs-on-amd64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: runs-on,runner=2cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"

