---
name: Vault Testcase

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/vault-testcase.yaml

jobs:
  changes:
    uses: ./.github/workflows/changes.yaml

  github-hosted:
    needs: changes
    if: ${{ needs.changes.outputs.vault == 'true' }}
    uses: ./.github/workflows/vault.yaml
    with:
      runs-on: ubuntu-22.04

  self-hosted-containers:
    needs: changes
    if: ${{ needs.changes.outputs.vault == 'true' }}
    strategy:
      matrix:
        architecture:
        - amd64
        - arm64
        scope:
        - org-${{ github.repository_owner_id }}
        - repo-${{ github.repository_id }}
        runtime:
        - k8s
    uses: ./.github/workflows/vault.yaml
    with:
      runs-on: "${{ matrix.scope }}-${{ matrix.architecture }}-${{ matrix.runtime }}"

  self-hosted-org-vm:
    needs: changes
    if: ${{ needs.changes.outputs.vault == 'true' }}
    strategy:
      matrix:
        architecture:
        - x64
        - arm64
    uses: ./.github/workflows/vault.yaml
    with:
      runs-on: runs-on,runner=1cpu-linux-${{ matrix.architecture }},run-id=${{ github.run_id }}
