name: Vault Secret Isolation Test
on:
  workflow_call:
    inputs:
      container:
        default: ubuntu:22.04
        required: false
        type: string
      runs-on:
        default: ubuntu-22.04
        required: false
        type: string
      from-secret:
        type: string
        default: secret/data/github-actions/test
        required: false
      read-key: 
        type: string
        default: status
        required: false
      export-as:
        type: string
        default: PROOF_OF_CONCEPT
        required: false
      expected-value:
        type: string
        default: success
        required: false
  workflow_dispatch:
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      from-secret:
        type: string
        default: secret/data/github-actions/test
        required: false
      read-key: 
        type: string
        default: status
        required: false
      export-as:
        type: string
        default: PROOF_OF_CONCEPT
        required: false
      expected-value:
        type: string
        default: success
        required: false

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ inputs.runs-on }}
    container: ${{ inputs.container }}
    steps:
    - id: fetch
      uses: rancher-eio/read-vault-secrets@isolation
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
        command: |
          test "${{ env.PROOF_OF_CONCEPT }}" = "success"
    # - id: validate
    #   run: |
    #     test "${{ steps.fetch.outputs.vault_secrets }}" = "${{ inputs.expected-value }}"

    - id: validate_empty_env
      run: |
        test -z "${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}"
        
    - id: validate_empty_output
      run: |
        test -z "${{ steps.fetch.outputs.vault_secrets }}"
