name: Vault Secrets Isolation
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/vault-secrets-isolation.yaml
  workflow_dispatch:

jobs:
  get-secrets:
    uses: rancher-eio/read-vault-secrets/.github/workflows/fetch-and-encrypt-vault-secrets.yaml@isolation
    with:
      vault_secrets: |
        secret/data/github-actions/test status | FOO ;
        secret/data/github-actions/test status | BAR
    secrets:
      CI_ENCRYPTION_KEY: ${{ secrets.CI_ENCRYPTION_KEY }}  

  use-secrets:
    runs-on: ubuntu-24.04
    needs: get-secrets
    steps:
    - uses: actions/checkout@v3
    - name: ACTIONS_ID_TOKEN_REQUEST_TOKEN is empty
      run: test -z "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
    - name: ENV does not contain secrets
      run: test -z "${FOO}" && test -z "${BAR}"
    - name: VAULT_TOKEN is empty
      run: test -z "${VAULT_TOKEN}" 
    - name: Verify Secrets Output from Needs (Debug)
      shell: bash
      run: |
        echo "Encrypted Secrets Received via needs: ${{ needs.get-secrets.outputs.secrets }}"
        echo "Length: $(echo -n '${{ needs.get-secrets.outputs.secrets }}' | wc -c)"          
    - name: Decrypt secrets
      id: decrypt
      uses: rancher-eio/read-vault-secrets/decrypt-vault-secrets@isolation
      env:
        CI_ENCRYPTION_KEY: ${{ secrets.CI_ENCRYPTION_KEY }}
      with:
        encrypted_secrets: ${{ needs.get-secrets.outputs.secrets }}
        
    - name: Decrypted secrets are available as outputs
      run: |
        test "${{ fromJSON(steps.decrypt.outputs.secrets).FOO }}" = "success" \
        && test "${{ fromJSON(steps.decrypt.outputs.secrets).BAR }}" = "success"
