---
name: Vault Variety Show

on:
  push:
    branches:
    - main
    paths:
    - .github/actions/read-vault-secrets/action.yml
    - .github/workflows/vault-variety-show.yaml

jobs:
  default:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04
    steps:
    - id: fetch
      uses: rancher-eio/test/.github/actions/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | FOO ;
          secret/data/github-actions/test status | BAR
    - name: ENV does not contain secrets
      run: test -z "${FOO}" && test -z "${BAR}"
    - name: VAULT_TOKEN is empty
      run: test -z "${VAULT_TOKEN}"
    - name: ACTIONS_ID_TOKEN_REQUEST_TOKEN is DISCARDED
      run: test "${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" = "DISCARDED\r"
    - name: secrets are available as outputs
      run: |
        true \
        && test "${{ steps.fetch.outputs.declared }}" = "success" \
        && test "${{ steps.fetch.outputs.undeclared }}" = "success" \
        && test "${{ steps.fetch.outputs.FOO }}" = "success" \
        && test "${{ steps.fetch.outputs.BAR }}" = "success"
        
