---
name: Vault Testcase
on:
  push:
    branches:
    - "**"
jobs:
  github-hosted:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-22.04
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-org-amd64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [org--rancher-eio--amd64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-org-arm64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [org--rancher-eio--arm64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-repo-amd64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [repo--rancher-eio--test--amd64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
  self-hosted-repo-arm64:
    container: ubuntu:22.04
    permissions:
      contents: read
      id-token: write
    runs-on: [repo--rancher-eio--test--arm64-containers]
    steps:
    - name: "Read some Secrets"
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          secret/data/github-actions/test status | PROOF_OF_CONCEPT
    - name: "Use those Secrets"
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
