name: Vault
on:
  workflow_call: &workflow_call
    inputs:
      runs-on:
        default: ubuntu-latest
        required: false
        type: string
      from-secret:
        type: string
        default: secret/data/github-actions/test
        required: false
      read-key: 
        type: string
        default: status
        required: false
      export-as:
        type: string
        default: PROOF_OF_CONCEPT
        required: false
      expected-value:
        type: string
        default: success
        required: false
  workflow_dispatch: *workflow_call
jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ inputs.runs-on }}
    steps:
    - id: fetch
      uses: rancher-eio/read-vault-secrets@main
      with:
        secrets: |
          ${{ inputs.from-secret }} ${{ inputs.read-key }} | ${{ inputs.export-as }}
    - id: validate
      run: |
        test "${{ env.PROOF_OF_CONCEPT }}" = "success"
