name: WireGuard Vault Access

on:
  workflow_dispatch: 

jobs:
  test-wireguard:
    runs-on: ubuntu-latest
    steps:
      - name: Install WireGuard
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf

      - name: Setup Dynamic WireGuard Connection
        run: |
          PRIVATE_KEY=$(wg genkey)
          PUBLIC_KEY=$(echo $PRIVATE_KEY | wg pubkey)
          
          echo "Generated key pair for this runner"
          echo "Public key: $PUBLIC_KEY"
          
          echo "[Interface]
          PrivateKey = $PRIVATE_KEY
          Address = 10.34.0.100/32
          
          [Peer]
          PublicKey = ${{ secrets.WIREGUARD_SERVER_PUBLIC_KEY }}
          Endpoint = ${{ secrets.WIREGUARD_SERVER_ENDPOINT }}
          AllowedIPs = 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
          PersistentKeepalive = 25" | sudo tee /etc/wireguard/wg0.conf
          
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          echo "WireGuard connection established"
          
          sudo wg show

      - name: Test Connection
        run: |
          ping -c 4 10.34.0.1
          #ping -c 4 backend-podinfo.podinfo.svc.cluster.local
          ip route

      - name: Disconnect WireGuard
        if: always()
        run: |
          sudo wg-quick down wg0
          echo "WireGuard connection terminated"
