---
name: With Runners

on:
  workflow_call:
    inputs:
      changes-workflow:
        type: string
        default: changes.yaml
        required: true
      needs-changes:
        type: boolean
        default: true
        required: true
      on-change:
        type: string
        default: vault
        required: false
      workflow:
        type: string
        default: vault.yaml
        required: true
  workflow_dispatch:
    inputs:
      changes-workflow:
        type: string
        default: changes.yaml
        required: true
      needs-changes:
        type: boolean
        default: true
        required: true
      on-change:
        type: string
        default: vault
        required: false
      workflow:
        type: string
        default: vault.yaml
        required: true

jobs:
  changes:
    uses: ./.github/workflows/${{ inputs.changes-workflow }}

  github-hosted:
    needs: changes
    if: ${{ inputs.needs-changes && (needs.changes.outputs[inputs.on-change] == 'true') }}
    uses: ./.github/workflows/${{ inputs.workflow }}@${{github.sha}}
    with:
      runs-on: ubuntu-22.04

  self-hosted-container:
    needs: changes
    if: ${{ inputs.needs-changes && (needs.changes.outputs[inputs.on-change] == 'true') }}
    strategy:
      matrix:
        architecture:
        - amd64
        - arm64
        scope:
        - org-${{ github.repository_owner_id }}
        - repo-${{ github.repository_id }}
        runtime:
        - k8s
    uses: ./.github/workflows/${{ inputs.workflow }}@${{github.sha}}
    with:
      runs-on: "${{ matrix.scope }}-${{ matrix.architecture }}-${{ matrix.runtime }}"

  self-hosted-virtual-machine:
    needs: changes
    if: ${{ inputs.needs-changes && (needs.changes.outputs[inputs.on-change] == 'true') }}
    strategy:
      matrix:
        architecture:
        - x64
        - arm64
    uses: ./.github/workflows/${{ inputs.workflow }}@${{github.sha}}
    with:
      runs-on: runs-on,runner=1cpu-linux-${{ matrix.architecture }},run-id=${{ github.run_id }}
