---
name: With Runners

on:
  workflow_call:
    inputs:
      workflow:
        type: string
        default: vault
        required: true
      github-hosted:
        type: boolean
        default: true
      self-hosted:
        type: boolean
        default: true
      containers:
        type: boolean
        default: true
      virtual-machines:
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      workflow:
        type: string
        default: vault
        required: true
      github-hosted:
        type: boolean
        default: true
      self-hosted:
        type: boolean
        default: true
      containers:
        type: boolean
        default: true
      virtual-machines:
        type: boolean
        default: true

jobs:
  github-hosted:
    if: ${{ inputs.github-hosted }}
    uses: ./.github/workflows/${{ inputs.workflow }}.yaml
    with:
      runs-on: ubuntu-22.04

  self-hosted-container:
    if: ${{ inputs.self-hosted && inputs.containers }}
    strategy:
      matrix:
        architecture:
        - amd64
        - arm64
        scope:
        - org-${{ github.repository_owner_id }}
        - repo-${{ github.repository_id }}
        runtime:
        - k8s
    uses: ./.github/workflows/${{ inputs.workflow }}.yaml
    with:
      runs-on: "${{ matrix.scope }}-${{ matrix.architecture }}-${{ matrix.runtime }}"

  self-hosted-virtual-machine:
    if: ${{ inputs.self-hosted && inputs.virtual-machines }}
    strategy:
      matrix:
        architecture:
        - x64
        - arm64
    uses: ./.github/workflows/${{ inputs.workflow }}.yaml
    with:
      runs-on: runs-on,runner=1cpu-linux-${{ matrix.architecture }},run-id=${{ github.run_id }}
